# Introduction à [NumPy](https://www.python-simple.com/python-numpy/creation-numpy.php)

## 1-Pourquoi NumPy ?

Le data analyste est confronté à des ensembles de données complexes et massifs. Les structures de données natives de Python, comme les listes, peuvent être limitées pour manipuler efficacement ces données.

C'est là que NumPy entre en jeu.

**NumPy**, abréviation de *Numerical Python*, est une bibliothèque essentielle en Python pour effectuer des opérations numériques sur des tableaux de données. Elle offre des fonctionnalités puissantes pour la manipulation de données et est largement utilisée dans le domaine de l'analyse des données et du machine learning.

## 2-Qu'est-ce qu'un Array NumPy ?

Un tableau NumPy, ou array, est une structure de données similaire à une liste Python, mais avec des avantages significatifs. La principale différence réside dans la capacité des arrays NumPy à effectuer des opérations complexes de manière efficace. Ils facilitent également le stockage et la manipulation des données.

Par exemple, considérons le calcul de la moyenne d'un ensemble de données. Alors que dans une liste Python, vous devriez coder la fonction vous-même, NumPy offre une fonction existante:

```python
import numpy as np

data = [1800, 1500, 2200, 3000, 2172]
average = np.mean(data)


NumPy simplifie ainsi de nombreuses opérations mathématiques et devient particulièrement puissant lorsque vous travaillez avec de grandes quantités de données.

## Différences clés entre Arrays NumPy et Listes Python

- **Performance** : Les opérations avec les arrays NumPy sont environ 30 fois plus rapides que les listes Python, surtout avec des ensembles de données volumineux.

- **Type unique** : Contrairement aux listes Python, les arrays NumPy ne peuvent contenir qu'un seul type de données. Cela permet une manipulation plus cohérente et des opérations plus rapides.

- **Fonctions mathématiques** : NumPy offre une pléthore de fonctions mathématiques pour effectuer des opérations complexes sur les données.






## 3-Installation de NumPy

Si vous avez installé Anaconda, alors NumPy est déjà installé sur votre système. Mais dans le cas contraire, tapez cette ligne de commande dans votre terminal :

```bash
pip install numpy
```


## 4-Utiliser la bibliothèque NumPy

Pour utiliser la bibliothèque NumPy en Python, vous devez l'importer dans votre code. Voici comment le faire :

```python
import numpy as np


```

### 4-1-Création

#### Création d'Arrays NumPy : à partir d'une Liste Python

```python
import numpy as np

data = [1800, 1500, 2200, 3000, 2172]
numpy_array = np.array(data)
```

#### Fonctions NumPy couramment utilisées

- **`np.zeros(n)`**: Crée un array rempli de zéros avec `n` éléments.

- **`np.ones(n)`**: Crée un array rempli de uns avec `n` éléments.

- **`np.arange(i, j, p)`**: Crée un array avec une séquence linéaire de `i` à `j` par pas de `p`.

- **`np.linspace(i, j, n)`**: Crée un array de `n` valeurs espacées uniformément entre `i` et `j`.


### 4-2- Dimensions

Pour connaître la dimension d’un tableau, on peut afficher la valeur de l’attribut `ndim` :

```python


print("ndim tableau : ", numpy_array.ndim)

```

Le nombre d’éléments dans le tableau peut s’obtenir par l’attribut size ou par la fonction `size()` de Numpy :
```python
print("size tableau : ", numpy_array.size)
```

L’attribut shape retourne un n-uplet indiquant la longueur pour chaque dimension du tableau :
```python
print("size tableau : ", numpy_array.shape)


```

### 4-3-Sélection d'Éléments dans un Array NumPy


#### Accès au premier élément :

```python
numpy_array[0]  # Accès au troisième élément
```



#### Accès au dernier élément :

```python
numpy_array[2]  # Accès au troisième élément
```



#### Accès à un seul élément :

```python
numpy_array[2]  # Accès au troisième élément
```


#### Accès à plusieurs éléments contigus :
```python
numpy_array[1:4]  # Sélectionne les éléments de l'indice 1 à 3
```
#### Accès à plusieurs éléments selon une condition :
```python
numpy_array[numpy_array > 2000]  # Sélectionne les valeurs supérieures à 2000
```

#### Accès à l’aide de booléens

Pour extraire ou non des éléments d’un tableu, on peut utiliser des tableaux de booléens en tant que masques. L’idée est de fournir un tableau de booléens (un masque) de même dimension que celui pour lequel on désire extraire des éléments sous certaines conditions. Lorsque la valeur du booléen dans le masque vaut True, l’élément correspondant du tableau est retourné ; sinon, il ne l’est pas.

```python
tableau = np.array([0, 3, 2, 5, 1, 4])
res = tableau[[True, False, True, False, True, True]]
print(res)

``` 


### 4-4-Modification

#### Remplacement d'Éléments
Pour remplacer les valeurs d'un tableau, on utilise le signe égal (=) :

```python
tableau = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tableau[0] = [11, 22, 33]
print(tableau)
```

In [4]:
tableau = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tableau[0] = [11, 22, 33]
print(tableau)

[[11 22 33]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Si on fournit un scalaire lors du remplacement, la valeur sera répétée pour tous les éléments de la dimension :

In [5]:
tableau[0] = 100
print(tableau)

[[100 100 100]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]


#### Ajout d'Éléments
Pour ajouter des éléments, on utilise la fonction `append()` de NumPy. Il est important de noter que l'appel à cette fonction ne modifie pas l'objet d'origine. Si on souhaite que les modifications soient apportées à cet objet, il faut le réaffecter



In [6]:
t_1 = np.array([1, 3, 5])
print("t_1 : ", t_1)
t_1 = np.append(t_1, 1)
print("t_1 après l'ajout : ", t_1)

t_1 :  [1 3 5]
t_1 après l'ajout :  [1 3 5 1]


####  Suppression d'Éléments
Pour supprimer des éléments, on utilise la fonction delete() de NumPy :




In [8]:
print("t_1 : ", t_1)
np.delete(t_1, (-1))


t_1 :  [1 3 5 1]


array([1, 3, 5])

Note : pour que la suppression soit effective, on assigne le résultat de np.delete() à l’objet.



#### Comment changer la forme du tableau NumPy ?

Vous pouvez donner une autre forme à votre tableau sans modifier les données qu’il comporte, et cela grâce à la méthode `np.reshape()`.


In [7]:
import numpy as np

a = np.array([3, 6, 9, 12])
print('Forme initiale :', '\n', a)

reshaped_array = np.reshape(a, (2, 2))
print(reshaped_array)


Forme initiale : 
 [ 3  6  9 12]
[[ 3  6]
 [ 9 12]]


#### Aplatir un tableau NumPy

Il arrive parfois que vous vouliez réduire un tableau multidimensionnel à un tableau à une seule dimension. Pour cela, vous pouvez utiliser les méthodes `flatten()` et `ravel()`.

```python
import numpy as np

# Exemple d'utilisation de flatten()
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = array_2d.flatten()

# Exemple d'utilisation de ravel()
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
raveled_array = array_2d.ravel()


### 4-6-Opérations sur les Tableaux en NumPy

#### Opérateurs + et -
Lorsque l'opérateur + (-) est utilisé entre deux tableaux de même dimension, une addition (soustraction) terme à terme est effectuée :

In [10]:
t_1 = np.array([1, 2, 3, 4])
t_2 = np.array([5, 6, 7, 8])
t_3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
t_4 = np.array([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])

print(f"{t_1 + t_2}")
print(f"{t_3 + t_4}")
print(f"{t_1 - t_2}")


[ 6  8 10 12]
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[-4 -4 -4 -4]


### 4-6-Méthodes [NumPy Utiles](https://www.python-simple.com/python-numpy/fonctions-numpy.php)

```python
numpy_array.mean()  # Calcul de la moyenne
numpy_array.max()   # Valeur maximale
numpy_array.min()   # Valeur minimale
numpy_array.argmax()  # Indice de la valeur maximale
numpy_array.argmin()  # Indice de la valeur minimale
numpy_array.sort()   # Tri des éléments
numpy_array.sum()    # Somme des éléments


NumPy offre une multitude de méthodes pour manipuler et effectuer des opérations mathématiques sur les arrays. Vous pouvez explorer davantage ces fonctionnalités dans la documentation officielle de NumPy.

### Conclusion
En résumé, NumPy est un outil indispensable en analyse des données. Il vous permet d'effectuer des opérations numériques efficaces sur des ensembles de données massifs, facilitant ainsi votre travail en Master 2. Explorez les nombreuses fonctionnalités de NumPy et préparez-vous à plonger plus profondément dans la manipulation de données lors de votre parcours académique. Happy coding! 🚀
